// 이 파일은 자동 생성됨 — server/src/data/kric-station-codes-2026-05-11.xlsx 기반
// 1~9호선 서울교통공사/서울메트로9호선 직영 구간 메타 + 역 데이터 + 환승역
// ⚠️ 4호선 KORAIL/남양주 구간(선바위~오이도, 진접 연장)은 별도 (constants/line4Stations.ts)

import type { ColorKey } from "../theme/colors";

export type LineKey = '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';

/** 호선별 메타 */
export interface LineMeta {
  key: LineKey;
  name: string;
  /** theme/colors의 key (예: 'line4') */
  colorKey: ColorKey;
  /** KRIC stationCongestion API 데이터 제공 여부 (9호선은 미지원) */
  congestionSupported: boolean;
  /** 상행/하행 종착역 (방면 표시용) */
  upTerminus: string;
  downTerminus: string;
  /** 사용자에게 보여줄 방면 라벨 */
  upLabel: string;
  downLabel: string;
}

export const LINES: Record<LineKey, LineMeta> = {
  '1': {
    key: '1',
    name: '1호선',
    colorKey: 'line1',
    congestionSupported: true,
    upTerminus: '서울역',
    downTerminus: '동묘앞',
    upLabel: '서울역 방면',
    downLabel: '동묘앞 방면',
  },
  '2': {
    key: '2',
    name: '2호선',
    colorKey: 'line2',
    congestionSupported: true,
    upTerminus: '내선순환',
    downTerminus: '외선순환',
    upLabel: '내선순환',
    downLabel: '외선순환',
  },
  '3': {
    key: '3',
    name: '3호선',
    colorKey: 'line3',
    congestionSupported: true,
    upTerminus: '대화',
    downTerminus: '오금',
    upLabel: '대화 방면',
    downLabel: '오금 방면',
  },
  '4': {
    key: '4',
    name: '4호선',
    colorKey: 'line4',
    congestionSupported: true,
    upTerminus: '당고개',
    downTerminus: '오이도',
    upLabel: '당고개 방면',
    downLabel: '오이도 방면',
  },
  '5': {
    key: '5',
    name: '5호선',
    colorKey: 'line5',
    congestionSupported: true,
    upTerminus: '방화',
    downTerminus: '하남검단산',
    upLabel: '방화 방면',
    downLabel: '하남 방면',
  },
  '6': {
    key: '6',
    name: '6호선',
    colorKey: 'line6',
    congestionSupported: true,
    upTerminus: '응암순환',
    downTerminus: '신내',
    upLabel: '응암 방면',
    downLabel: '신내 방면',
  },
  '7': {
    key: '7',
    name: '7호선',
    colorKey: 'line7',
    congestionSupported: true,
    upTerminus: '장암',
    downTerminus: '석남',
    upLabel: '장암 방면',
    downLabel: '석남 방면',
  },
  '8': {
    key: '8',
    name: '8호선',
    colorKey: 'line8',
    congestionSupported: true,
    upTerminus: '별내',
    downTerminus: '모란',
    upLabel: '별내 방면',
    downLabel: '모란 방면',
  },
  '9': {
    key: '9',
    name: '9호선',
    colorKey: 'line9',
    congestionSupported: false,
    upTerminus: '개화',
    downTerminus: '중앙보훈병원',
    upLabel: '개화 방면',
    downLabel: '중앙보훈병원 방면',
  },
};

/** 한 호선의 역 1개 */
export interface LineStationEntry {
  stinCd: string;
  stinNm: string;
  /** 괄호 없는 단순 이름 (검색/표시용) */
  simpleName: string;
}

/** 호선별 역 목록 (운행 순서) */
export const LINE_STATIONS: Record<LineKey, LineStationEntry[]> = {
  '1': [
    { stinCd: '150', stinNm: '서울역', simpleName: '서울역' },
    { stinCd: '151', stinNm: '시청', simpleName: '시청' },
    { stinCd: '152', stinNm: '종각', simpleName: '종각' },
    { stinCd: '153', stinNm: '종로3가', simpleName: '종로3가' },
    { stinCd: '154', stinNm: '종로5가', simpleName: '종로5가' },
    { stinCd: '155', stinNm: '동대문', simpleName: '동대문' },
    { stinCd: '156', stinNm: '신설동', simpleName: '신설동' },
    { stinCd: '157', stinNm: '제기동', simpleName: '제기동' },
    { stinCd: '158', stinNm: '청량리(서울시립대입구)', simpleName: '청량리' },
    { stinCd: '159', stinNm: '동묘앞', simpleName: '동묘앞' },
  ],
  '2': [
    { stinCd: '201', stinNm: '시청', simpleName: '시청' },
    { stinCd: '202', stinNm: '을지로입구', simpleName: '을지로입구' },
    { stinCd: '203', stinNm: '을지로3가', simpleName: '을지로3가' },
    { stinCd: '204', stinNm: '을지로4가', simpleName: '을지로4가' },
    { stinCd: '205', stinNm: '동대문역사문화공원', simpleName: '동대문역사문화공원' },
    { stinCd: '206', stinNm: '신당', simpleName: '신당' },
    { stinCd: '207', stinNm: '상왕십리', simpleName: '상왕십리' },
    { stinCd: '208', stinNm: '왕십리', simpleName: '왕십리' },
    { stinCd: '209', stinNm: '한양대', simpleName: '한양대' },
    { stinCd: '210', stinNm: '뚝섬', simpleName: '뚝섬' },
    { stinCd: '211', stinNm: '성수', simpleName: '성수' },
    { stinCd: '212', stinNm: '건대입구', simpleName: '건대입구' },
    { stinCd: '213', stinNm: '구의(광진구청)', simpleName: '구의' },
    { stinCd: '214', stinNm: '강변(동서울터미널)', simpleName: '강변' },
    { stinCd: '215', stinNm: '잠실나루', simpleName: '잠실나루' },
    { stinCd: '216', stinNm: '잠실(송파구청)', simpleName: '잠실' },
    { stinCd: '217', stinNm: '잠실새내', simpleName: '잠실새내' },
    { stinCd: '218', stinNm: '종합운동장', simpleName: '종합운동장' },
    { stinCd: '219', stinNm: '삼성(무역센터)', simpleName: '삼성' },
    { stinCd: '220', stinNm: '선릉', simpleName: '선릉' },
    { stinCd: '221', stinNm: '역삼', simpleName: '역삼' },
    { stinCd: '222', stinNm: '강남', simpleName: '강남' },
    { stinCd: '223', stinNm: '교대(법원.검찰청)', simpleName: '교대' },
    { stinCd: '224', stinNm: '서초', simpleName: '서초' },
    { stinCd: '225', stinNm: '방배', simpleName: '방배' },
    { stinCd: '226', stinNm: '사당', simpleName: '사당' },
    { stinCd: '227', stinNm: '낙성대', simpleName: '낙성대' },
    { stinCd: '228', stinNm: '서울대입구(관악구청)', simpleName: '서울대입구' },
    { stinCd: '229', stinNm: '봉천', simpleName: '봉천' },
    { stinCd: '230', stinNm: '신림', simpleName: '신림' },
    { stinCd: '231', stinNm: '신대방', simpleName: '신대방' },
    { stinCd: '232', stinNm: '구로디지털단지', simpleName: '구로디지털단지' },
    { stinCd: '233', stinNm: '대림(구로구청)', simpleName: '대림' },
    { stinCd: '234', stinNm: '신도림', simpleName: '신도림' },
    { stinCd: '234-4', stinNm: '까치산', simpleName: '까치산' },
    { stinCd: '235', stinNm: '문래', simpleName: '문래' },
    { stinCd: '236', stinNm: '영등포구청', simpleName: '영등포구청' },
    { stinCd: '237', stinNm: '당산', simpleName: '당산' },
    { stinCd: '238', stinNm: '합정', simpleName: '합정' },
    { stinCd: '239', stinNm: '홍대입구', simpleName: '홍대입구' },
    { stinCd: '240', stinNm: '신촌', simpleName: '신촌' },
    { stinCd: '241', stinNm: '이대', simpleName: '이대' },
    { stinCd: '242', stinNm: '아현', simpleName: '아현' },
    { stinCd: '243', stinNm: '충정로(경기대입구)', simpleName: '충정로' },
    { stinCd: '244', stinNm: '용답', simpleName: '용답' },
    { stinCd: '245', stinNm: '신답', simpleName: '신답' },
    { stinCd: '246', stinNm: '신설동', simpleName: '신설동' },
    { stinCd: '247', stinNm: '도림천', simpleName: '도림천' },
    { stinCd: '248', stinNm: '양천구청', simpleName: '양천구청' },
    { stinCd: '249', stinNm: '신정네거리', simpleName: '신정네거리' },
    { stinCd: '250', stinNm: '용두(동대문구청)', simpleName: '용두' },
  ],
  '3': [
    { stinCd: '309', stinNm: '지축', simpleName: '지축' },
    { stinCd: '310', stinNm: '구파발', simpleName: '구파발' },
    { stinCd: '311', stinNm: '연신내', simpleName: '연신내' },
    { stinCd: '312', stinNm: '불광', simpleName: '불광' },
    { stinCd: '313', stinNm: '녹번', simpleName: '녹번' },
    { stinCd: '314', stinNm: '홍제', simpleName: '홍제' },
    { stinCd: '315', stinNm: '무악재', simpleName: '무악재' },
    { stinCd: '316', stinNm: '독립문', simpleName: '독립문' },
    { stinCd: '317', stinNm: '경복궁(정부서울청사)', simpleName: '경복궁' },
    { stinCd: '318', stinNm: '안국', simpleName: '안국' },
    { stinCd: '319', stinNm: '종로3가', simpleName: '종로3가' },
    { stinCd: '320', stinNm: '을지로3가', simpleName: '을지로3가' },
    { stinCd: '321', stinNm: '충무로', simpleName: '충무로' },
    { stinCd: '322', stinNm: '동대입구', simpleName: '동대입구' },
    { stinCd: '323', stinNm: '약수', simpleName: '약수' },
    { stinCd: '324', stinNm: '금호', simpleName: '금호' },
    { stinCd: '325', stinNm: '옥수', simpleName: '옥수' },
    { stinCd: '326', stinNm: '압구정', simpleName: '압구정' },
    { stinCd: '327', stinNm: '신사', simpleName: '신사' },
    { stinCd: '328', stinNm: '잠원', simpleName: '잠원' },
    { stinCd: '329', stinNm: '고속터미널', simpleName: '고속터미널' },
    { stinCd: '330', stinNm: '교대(법원.검찰청)', simpleName: '교대' },
    { stinCd: '331', stinNm: '남부터미널(예술의전당)', simpleName: '남부터미널' },
    { stinCd: '332', stinNm: '양재(서초구청)', simpleName: '양재' },
    { stinCd: '333', stinNm: '매봉', simpleName: '매봉' },
    { stinCd: '334', stinNm: '도곡', simpleName: '도곡' },
    { stinCd: '335', stinNm: '대치', simpleName: '대치' },
    { stinCd: '336', stinNm: '학여울', simpleName: '학여울' },
    { stinCd: '337', stinNm: '대청', simpleName: '대청' },
    { stinCd: '338', stinNm: '일원', simpleName: '일원' },
    { stinCd: '339', stinNm: '수서', simpleName: '수서' },
    { stinCd: '340', stinNm: '가락시장', simpleName: '가락시장' },
    { stinCd: '341', stinNm: '경찰병원', simpleName: '경찰병원' },
    { stinCd: '342', stinNm: '오금', simpleName: '오금' },
  ],
  '4': [
    { stinCd: '409', stinNm: '불암산(당고개)', simpleName: '불암산' },
    { stinCd: '410', stinNm: '상계', simpleName: '상계' },
    { stinCd: '411', stinNm: '노원', simpleName: '노원' },
    { stinCd: '412', stinNm: '창동', simpleName: '창동' },
    { stinCd: '413', stinNm: '쌍문', simpleName: '쌍문' },
    { stinCd: '414', stinNm: '수유(강북구청)', simpleName: '수유' },
    { stinCd: '415', stinNm: '미아', simpleName: '미아' },
    { stinCd: '416', stinNm: '미아사거리', simpleName: '미아사거리' },
    { stinCd: '417', stinNm: '길음', simpleName: '길음' },
    { stinCd: '418', stinNm: '성신여대입구(돈암)', simpleName: '성신여대입구' },
    { stinCd: '419', stinNm: '한성대입구(삼선교)', simpleName: '한성대입구' },
    { stinCd: '420', stinNm: '혜화', simpleName: '혜화' },
    { stinCd: '421', stinNm: '동대문', simpleName: '동대문' },
    { stinCd: '422', stinNm: '동대문역사문화공원', simpleName: '동대문역사문화공원' },
    { stinCd: '423', stinNm: '충무로', simpleName: '충무로' },
    { stinCd: '424', stinNm: '명동', simpleName: '명동' },
    { stinCd: '425', stinNm: '회현(남대문시장)', simpleName: '회현' },
    { stinCd: '426', stinNm: '서울역', simpleName: '서울역' },
    { stinCd: '427', stinNm: '숙대입구(갈월)', simpleName: '숙대입구' },
    { stinCd: '428', stinNm: '삼각지', simpleName: '삼각지' },
    { stinCd: '429', stinNm: '신용산', simpleName: '신용산' },
    { stinCd: '430', stinNm: '이촌(국립중앙박물관)', simpleName: '이촌' },
    { stinCd: '431', stinNm: '동작(현충원)', simpleName: '동작' },
    { stinCd: '432', stinNm: '총신대입구(이수)', simpleName: '총신대입구' },
    { stinCd: '433', stinNm: '사당', simpleName: '사당' },
    { stinCd: '434', stinNm: '남태령', simpleName: '남태령' },
  ],
  '5': [
    { stinCd: '2511', stinNm: '방화', simpleName: '방화' },
    { stinCd: '2512', stinNm: '개화산', simpleName: '개화산' },
    { stinCd: '2513', stinNm: '김포공항', simpleName: '김포공항' },
    { stinCd: '2514', stinNm: '송정', simpleName: '송정' },
    { stinCd: '2515', stinNm: '마곡', simpleName: '마곡' },
    { stinCd: '2516', stinNm: '발산', simpleName: '발산' },
    { stinCd: '2517', stinNm: '우장산', simpleName: '우장산' },
    { stinCd: '2518', stinNm: '화곡', simpleName: '화곡' },
    { stinCd: '2519', stinNm: '까치산', simpleName: '까치산' },
    { stinCd: '2520', stinNm: '신정(은행정)', simpleName: '신정' },
    { stinCd: '2521', stinNm: '목동', simpleName: '목동' },
    { stinCd: '2522', stinNm: '오목교(목동운동장앞)', simpleName: '오목교' },
    { stinCd: '2523', stinNm: '양평', simpleName: '양평' },
    { stinCd: '2524', stinNm: '영등포구청', simpleName: '영등포구청' },
    { stinCd: '2525', stinNm: '영등포시장', simpleName: '영등포시장' },
    { stinCd: '2526', stinNm: '신길', simpleName: '신길' },
    { stinCd: '2527', stinNm: '여의도', simpleName: '여의도' },
    { stinCd: '2528', stinNm: '여의나루', simpleName: '여의나루' },
    { stinCd: '2529', stinNm: '마포', simpleName: '마포' },
    { stinCd: '2530', stinNm: '공덕', simpleName: '공덕' },
    { stinCd: '2531', stinNm: '애오개', simpleName: '애오개' },
    { stinCd: '2532', stinNm: '충정로(경기대입구)', simpleName: '충정로' },
    { stinCd: '2533', stinNm: '서대문', simpleName: '서대문' },
    { stinCd: '2534', stinNm: '광화문(세종문화회관)', simpleName: '광화문' },
    { stinCd: '2535', stinNm: '종로3가(탑골공원)', simpleName: '종로3가' },
    { stinCd: '2536', stinNm: '을지로4가', simpleName: '을지로4가' },
    { stinCd: '2537', stinNm: '동대문역사문화공원', simpleName: '동대문역사문화공원' },
    { stinCd: '2538', stinNm: '청구', simpleName: '청구' },
    { stinCd: '2539', stinNm: '신금호', simpleName: '신금호' },
    { stinCd: '2540', stinNm: '행당', simpleName: '행당' },
    { stinCd: '2541', stinNm: '왕십리', simpleName: '왕십리' },
    { stinCd: '2542', stinNm: '마장', simpleName: '마장' },
    { stinCd: '2543', stinNm: '답십리', simpleName: '답십리' },
    { stinCd: '2544', stinNm: '장한평', simpleName: '장한평' },
    { stinCd: '2545', stinNm: '군자(능동)', simpleName: '군자' },
    { stinCd: '2546', stinNm: '아차산(어린이대공원후문)', simpleName: '아차산' },
    { stinCd: '2547', stinNm: '광나루(장신대)', simpleName: '광나루' },
    { stinCd: '2548', stinNm: '천호(풍납토성)', simpleName: '천호' },
    { stinCd: '2549', stinNm: '강동', simpleName: '강동' },
    { stinCd: '2550', stinNm: '길동', simpleName: '길동' },
    { stinCd: '2551', stinNm: '굽은다리(강동구민회관앞)', simpleName: '굽은다리' },
    { stinCd: '2552', stinNm: '명일', simpleName: '명일' },
    { stinCd: '2553', stinNm: '고덕', simpleName: '고덕' },
    { stinCd: '2554', stinNm: '상일동', simpleName: '상일동' },
    { stinCd: '2555', stinNm: '둔촌동', simpleName: '둔촌동' },
    { stinCd: '2556', stinNm: '올림픽공원(한국체대)', simpleName: '올림픽공원' },
    { stinCd: '2557', stinNm: '방이', simpleName: '방이' },
    { stinCd: '2558', stinNm: '오금', simpleName: '오금' },
    { stinCd: '2559', stinNm: '개롱', simpleName: '개롱' },
    { stinCd: '2560', stinNm: '거여', simpleName: '거여' },
    { stinCd: '2561', stinNm: '마천', simpleName: '마천' },
    { stinCd: '2562', stinNm: '강일', simpleName: '강일' },
    { stinCd: '2563', stinNm: '미사', simpleName: '미사' },
    { stinCd: '2564', stinNm: '하남풍산', simpleName: '하남풍산' },
    { stinCd: '2565', stinNm: '하남시청(덕풍.신장)', simpleName: '하남시청' },
    { stinCd: '2566', stinNm: '하남검단산역', simpleName: '하남검단산역' },
  ],
  '6': [
    { stinCd: '2611', stinNm: '응암', simpleName: '응암' },
    { stinCd: '2612', stinNm: '역촌', simpleName: '역촌' },
    { stinCd: '2613', stinNm: '불광', simpleName: '불광' },
    { stinCd: '2614', stinNm: '독바위', simpleName: '독바위' },
    { stinCd: '2615', stinNm: '연신내', simpleName: '연신내' },
    { stinCd: '2616', stinNm: '구산', simpleName: '구산' },
    { stinCd: '2617', stinNm: '새절(신사)', simpleName: '새절' },
    { stinCd: '2618', stinNm: '증산(명지대앞)', simpleName: '증산' },
    { stinCd: '2619', stinNm: '디지털미디어시티', simpleName: '디지털미디어시티' },
    { stinCd: '2620', stinNm: '월드컵경기장(성산)', simpleName: '월드컵경기장' },
    { stinCd: '2621', stinNm: '마포구청', simpleName: '마포구청' },
    { stinCd: '2622', stinNm: '망원', simpleName: '망원' },
    { stinCd: '2623', stinNm: '합정', simpleName: '합정' },
    { stinCd: '2624', stinNm: '상수', simpleName: '상수' },
    { stinCd: '2625', stinNm: '광흥창(서강)', simpleName: '광흥창' },
    { stinCd: '2626', stinNm: '대흥(서강대앞)', simpleName: '대흥' },
    { stinCd: '2627', stinNm: '공덕', simpleName: '공덕' },
    { stinCd: '2628', stinNm: '효창공원앞', simpleName: '효창공원앞' },
    { stinCd: '2629', stinNm: '삼각지', simpleName: '삼각지' },
    { stinCd: '2630', stinNm: '녹사평(용산구청)', simpleName: '녹사평' },
    { stinCd: '2631', stinNm: '이태원', simpleName: '이태원' },
    { stinCd: '2632', stinNm: '한강진', simpleName: '한강진' },
    { stinCd: '2633', stinNm: '버티고개', simpleName: '버티고개' },
    { stinCd: '2634', stinNm: '약수', simpleName: '약수' },
    { stinCd: '2635', stinNm: '청구', simpleName: '청구' },
    { stinCd: '2636', stinNm: '신당', simpleName: '신당' },
    { stinCd: '2637', stinNm: '동묘앞', simpleName: '동묘앞' },
    { stinCd: '2638', stinNm: '창신', simpleName: '창신' },
    { stinCd: '2639', stinNm: '보문', simpleName: '보문' },
    { stinCd: '2640', stinNm: '안암(고대병원앞)', simpleName: '안암' },
    { stinCd: '2641', stinNm: '고려대(종암)', simpleName: '고려대' },
    { stinCd: '2642', stinNm: '월곡(동덕여대)', simpleName: '월곡' },
    { stinCd: '2643', stinNm: '상월곡(한국과학기술연구원)', simpleName: '상월곡' },
    { stinCd: '2644', stinNm: '돌곶이', simpleName: '돌곶이' },
    { stinCd: '2645', stinNm: '석계', simpleName: '석계' },
    { stinCd: '2646', stinNm: '태릉입구', simpleName: '태릉입구' },
    { stinCd: '2647', stinNm: '화랑대(서울여대입구)', simpleName: '화랑대' },
    { stinCd: '2648', stinNm: '봉화산(서울의료원)', simpleName: '봉화산' },
    { stinCd: '2649', stinNm: '신내', simpleName: '신내' },
  ],
  '7': [
    { stinCd: '2711', stinNm: '장암', simpleName: '장암' },
    { stinCd: '2712', stinNm: '도봉산', simpleName: '도봉산' },
    { stinCd: '2713', stinNm: '수락산', simpleName: '수락산' },
    { stinCd: '2714', stinNm: '마들', simpleName: '마들' },
    { stinCd: '2715', stinNm: '노원', simpleName: '노원' },
    { stinCd: '2716', stinNm: '중계', simpleName: '중계' },
    { stinCd: '2717', stinNm: '하계', simpleName: '하계' },
    { stinCd: '2718', stinNm: '공릉(서울과학기술대)', simpleName: '공릉' },
    { stinCd: '2719', stinNm: '태릉입구', simpleName: '태릉입구' },
    { stinCd: '2720', stinNm: '먹골', simpleName: '먹골' },
    { stinCd: '2721', stinNm: '중화', simpleName: '중화' },
    { stinCd: '2722', stinNm: '상봉(시외버스터미널)', simpleName: '상봉' },
    { stinCd: '2723', stinNm: '면목', simpleName: '면목' },
    { stinCd: '2724', stinNm: '사가정', simpleName: '사가정' },
    { stinCd: '2725', stinNm: '용마산', simpleName: '용마산' },
    { stinCd: '2726', stinNm: '중곡', simpleName: '중곡' },
    { stinCd: '2727', stinNm: '군자(능동)', simpleName: '군자' },
    { stinCd: '2728', stinNm: '어린이대공원(세종대)', simpleName: '어린이대공원' },
    { stinCd: '2729', stinNm: '건대입구', simpleName: '건대입구' },
    { stinCd: '2730', stinNm: '자양(뚝섬한강공원)', simpleName: '자양' },
    { stinCd: '2731', stinNm: '청담', simpleName: '청담' },
    { stinCd: '2732', stinNm: '강남구청', simpleName: '강남구청' },
    { stinCd: '2733', stinNm: '학동', simpleName: '학동' },
    { stinCd: '2734', stinNm: '논현', simpleName: '논현' },
    { stinCd: '2735', stinNm: '반포', simpleName: '반포' },
    { stinCd: '2736', stinNm: '고속터미널', simpleName: '고속터미널' },
    { stinCd: '2737', stinNm: '내방', simpleName: '내방' },
    { stinCd: '2738', stinNm: '총신대입구(이수)', simpleName: '총신대입구' },
    { stinCd: '2739', stinNm: '남성', simpleName: '남성' },
    { stinCd: '2740', stinNm: '숭실대입구(살피재)', simpleName: '숭실대입구' },
    { stinCd: '2741', stinNm: '상도', simpleName: '상도' },
    { stinCd: '2742', stinNm: '장승배기', simpleName: '장승배기' },
    { stinCd: '2743', stinNm: '신대방삼거리', simpleName: '신대방삼거리' },
    { stinCd: '2744', stinNm: '보라매', simpleName: '보라매' },
    { stinCd: '2745', stinNm: '신풍', simpleName: '신풍' },
    { stinCd: '2746', stinNm: '대림(구로구청)', simpleName: '대림' },
    { stinCd: '2747', stinNm: '남구로', simpleName: '남구로' },
    { stinCd: '2748', stinNm: '가산디지털단지', simpleName: '가산디지털단지' },
    { stinCd: '2749', stinNm: '철산', simpleName: '철산' },
    { stinCd: '2750', stinNm: '광명사거리', simpleName: '광명사거리' },
    { stinCd: '2751', stinNm: '천왕', simpleName: '천왕' },
    { stinCd: '2752', stinNm: '온수(성공회대입구)', simpleName: '온수' },
  ],
  '8': [
    { stinCd: '2809', stinNm: '암사역사공원', simpleName: '암사역사공원' },
    { stinCd: '2811', stinNm: '암사', simpleName: '암사' },
    { stinCd: '2812', stinNm: '천호(풍납토성)', simpleName: '천호' },
    { stinCd: '2813', stinNm: '강동구청', simpleName: '강동구청' },
    { stinCd: '2814', stinNm: '몽촌토성(평화의문)', simpleName: '몽촌토성' },
    { stinCd: '2815', stinNm: '잠실(송파구청)', simpleName: '잠실' },
    { stinCd: '2816', stinNm: '석촌', simpleName: '석촌' },
    { stinCd: '2817', stinNm: '송파', simpleName: '송파' },
    { stinCd: '2818', stinNm: '가락시장', simpleName: '가락시장' },
    { stinCd: '2819', stinNm: '문정', simpleName: '문정' },
    { stinCd: '2820', stinNm: '장지', simpleName: '장지' },
    { stinCd: '2821', stinNm: '복정', simpleName: '복정' },
    { stinCd: '2822', stinNm: '산성', simpleName: '산성' },
    { stinCd: '2823', stinNm: '남한산성입구(성남법원.검찰청)', simpleName: '남한산성입구' },
    { stinCd: '2824', stinNm: '단대오거리', simpleName: '단대오거리' },
    { stinCd: '2825', stinNm: '신흥', simpleName: '신흥' },
    { stinCd: '2826', stinNm: '수진', simpleName: '수진' },
    { stinCd: '2827', stinNm: '모란', simpleName: '모란' },
    { stinCd: '2828', stinNm: '남위례', simpleName: '남위례' },
  ],
  '9': [
    { stinCd: '0901', stinNm: '개화', simpleName: '개화' },
    { stinCd: '0902', stinNm: '김포공항', simpleName: '김포공항' },
    { stinCd: '0903', stinNm: '공항시장', simpleName: '공항시장' },
    { stinCd: '0904', stinNm: '신방화', simpleName: '신방화' },
    { stinCd: '0905', stinNm: '마곡나루', simpleName: '마곡나루' },
    { stinCd: '0906', stinNm: '양천향교', simpleName: '양천향교' },
    { stinCd: '0907', stinNm: '가양', simpleName: '가양' },
    { stinCd: '0908', stinNm: '증미', simpleName: '증미' },
    { stinCd: '0909', stinNm: '등촌', simpleName: '등촌' },
    { stinCd: '0910', stinNm: '염창', simpleName: '염창' },
    { stinCd: '0911', stinNm: '신목동', simpleName: '신목동' },
    { stinCd: '0912', stinNm: '선유도', simpleName: '선유도' },
    { stinCd: '0913', stinNm: '당산', simpleName: '당산' },
    { stinCd: '0914', stinNm: '국회의사당', simpleName: '국회의사당' },
    { stinCd: '0915', stinNm: '여의도', simpleName: '여의도' },
    { stinCd: '0916', stinNm: '샛강', simpleName: '샛강' },
    { stinCd: '917', stinNm: '노량진', simpleName: '노량진' },
    { stinCd: '0918', stinNm: '노들', simpleName: '노들' },
    { stinCd: '0919', stinNm: '흑석(중앙대입구)', simpleName: '흑석' },
    { stinCd: '0920', stinNm: '동작(현충원)', simpleName: '동작' },
    { stinCd: '0921', stinNm: '구반포', simpleName: '구반포' },
    { stinCd: '0922', stinNm: '신반포', simpleName: '신반포' },
    { stinCd: '0923', stinNm: '고속터미널', simpleName: '고속터미널' },
    { stinCd: '0924', stinNm: '사평', simpleName: '사평' },
    { stinCd: '0925', stinNm: '신논현', simpleName: '신논현' },
    { stinCd: '926', stinNm: '언주', simpleName: '언주' },
    { stinCd: '927', stinNm: '선정릉', simpleName: '선정릉' },
    { stinCd: '928', stinNm: '삼성중앙', simpleName: '삼성중앙' },
    { stinCd: '929', stinNm: '봉은사', simpleName: '봉은사' },
    { stinCd: '930', stinNm: '종합운동장', simpleName: '종합운동장' },
    { stinCd: '931', stinNm: '삼전', simpleName: '삼전' },
    { stinCd: '932', stinNm: '석촌고분', simpleName: '석촌고분' },
    { stinCd: '933', stinNm: '석촌', simpleName: '석촌' },
    { stinCd: '934', stinNm: '송파나루', simpleName: '송파나루' },
    { stinCd: '935', stinNm: '한성백제', simpleName: '한성백제' },
    { stinCd: '936', stinNm: '올림픽공원(한국체대)', simpleName: '올림픽공원' },
    { stinCd: '937', stinNm: '둔촌오륜', simpleName: '둔촌오륜' },
    { stinCd: '938', stinNm: '중앙보훈병원', simpleName: '중앙보훈병원' },
  ],
};

/**
 * 환승역 매핑: 단순 역명 → 통과하는 호선 배열
 * 총 42개 환승역 (서울교통/9호선 직영 구간 한정)
 * 예: '사당' → ['2', '4'], '신도림' → ['1', '2']
 */
export const TRANSFER_STATIONS: Record<string, LineKey[]> = {
  '가락시장': ['3', '8'],
  '건대입구': ['2', '7'],
  '고속터미널': ['3', '7', '9'],
  '공덕': ['5', '6'],
  '교대': ['2', '3'],
  '군자': ['5', '7'],
  '김포공항': ['5', '9'],
  '까치산': ['2', '5'],
  '노원': ['4', '7'],
  '당산': ['2', '9'],
  '대림': ['2', '7'],
  '동대문': ['1', '4'],
  '동대문역사문화공원': ['2', '4', '5'],
  '동묘앞': ['1', '6'],
  '동작': ['4', '9'],
  '불광': ['3', '6'],
  '사당': ['2', '4'],
  '삼각지': ['4', '6'],
  '서울역': ['1', '4'],
  '석촌': ['8', '9'],
  '시청': ['1', '2'],
  '신당': ['2', '6'],
  '신설동': ['1', '2'],
  '약수': ['3', '6'],
  '여의도': ['5', '9'],
  '연신내': ['3', '6'],
  '영등포구청': ['2', '5'],
  '오금': ['3', '5'],
  '올림픽공원': ['5', '9'],
  '왕십리': ['2', '5'],
  '을지로3가': ['2', '3'],
  '을지로4가': ['2', '5'],
  '잠실': ['2', '8'],
  '종로3가': ['1', '3', '5'],
  '종합운동장': ['2', '9'],
  '천호': ['5', '8'],
  '청구': ['5', '6'],
  '총신대입구': ['4', '7'],
  '충무로': ['3', '4'],
  '충정로': ['2', '5'],
  '태릉입구': ['6', '7'],
  '합정': ['2', '6'],
};

/** KRIC stationCongestion이 지원하는 모든 simpleName Set (1~8호선) */
export const CONGESTION_SUPPORTED_NAMES: ReadonlySet<string> = new Set([
  '서울역',
  '시청',
  '종각',
  '종로3가',
  '종로5가',
  '동대문',
  '신설동',
  '제기동',
  '청량리',
  '동묘앞',
  '시청',
  '을지로입구',
  '을지로3가',
  '을지로4가',
  '동대문역사문화공원',
  '신당',
  '상왕십리',
  '왕십리',
  '한양대',
  '뚝섬',
  '성수',
  '건대입구',
  '구의',
  '강변',
  '잠실나루',
  '잠실',
  '잠실새내',
  '종합운동장',
  '삼성',
  '선릉',
  '역삼',
  '강남',
  '교대',
  '서초',
  '방배',
  '사당',
  '낙성대',
  '서울대입구',
  '봉천',
  '신림',
  '신대방',
  '구로디지털단지',
  '대림',
  '신도림',
  '까치산',
  '문래',
  '영등포구청',
  '당산',
  '합정',
  '홍대입구',
  '신촌',
  '이대',
  '아현',
  '충정로',
  '용답',
  '신답',
  '신설동',
  '도림천',
  '양천구청',
  '신정네거리',
  '용두',
  '지축',
  '구파발',
  '연신내',
  '불광',
  '녹번',
  '홍제',
  '무악재',
  '독립문',
  '경복궁',
  '안국',
  '종로3가',
  '을지로3가',
  '충무로',
  '동대입구',
  '약수',
  '금호',
  '옥수',
  '압구정',
  '신사',
  '잠원',
  '고속터미널',
  '교대',
  '남부터미널',
  '양재',
  '매봉',
  '도곡',
  '대치',
  '학여울',
  '대청',
  '일원',
  '수서',
  '가락시장',
  '경찰병원',
  '오금',
  '불암산',
  '상계',
  '노원',
  '창동',
  '쌍문',
  '수유',
  '미아',
  '미아사거리',
  '길음',
  '성신여대입구',
  '한성대입구',
  '혜화',
  '동대문',
  '동대문역사문화공원',
  '충무로',
  '명동',
  '회현',
  '서울역',
  '숙대입구',
  '삼각지',
  '신용산',
  '이촌',
  '동작',
  '총신대입구',
  '사당',
  '남태령',
  '방화',
  '개화산',
  '김포공항',
  '송정',
  '마곡',
  '발산',
  '우장산',
  '화곡',
  '까치산',
  '신정',
  '목동',
  '오목교',
  '양평',
  '영등포구청',
  '영등포시장',
  '신길',
  '여의도',
  '여의나루',
  '마포',
  '공덕',
  '애오개',
  '충정로',
  '서대문',
  '광화문',
  '종로3가',
  '을지로4가',
  '동대문역사문화공원',
  '청구',
  '신금호',
  '행당',
  '왕십리',
  '마장',
  '답십리',
  '장한평',
  '군자',
  '아차산',
  '광나루',
  '천호',
  '강동',
  '길동',
  '굽은다리',
  '명일',
  '고덕',
  '상일동',
  '둔촌동',
  '올림픽공원',
  '방이',
  '오금',
  '개롱',
  '거여',
  '마천',
  '강일',
  '미사',
  '하남풍산',
  '하남시청',
  '하남검단산역',
  '응암',
  '역촌',
  '불광',
  '독바위',
  '연신내',
  '구산',
  '새절',
  '증산',
  '디지털미디어시티',
  '월드컵경기장',
  '마포구청',
  '망원',
  '합정',
  '상수',
  '광흥창',
  '대흥',
  '공덕',
  '효창공원앞',
  '삼각지',
  '녹사평',
  '이태원',
  '한강진',
  '버티고개',
  '약수',
  '청구',
  '신당',
  '동묘앞',
  '창신',
  '보문',
  '안암',
  '고려대',
  '월곡',
  '상월곡',
  '돌곶이',
  '석계',
  '태릉입구',
  '화랑대',
  '봉화산',
  '신내',
  '장암',
  '도봉산',
  '수락산',
  '마들',
  '노원',
  '중계',
  '하계',
  '공릉',
  '태릉입구',
  '먹골',
  '중화',
  '상봉',
  '면목',
  '사가정',
  '용마산',
  '중곡',
  '군자',
  '어린이대공원',
  '건대입구',
  '자양',
  '청담',
  '강남구청',
  '학동',
  '논현',
  '반포',
  '고속터미널',
  '내방',
  '총신대입구',
  '남성',
  '숭실대입구',
  '상도',
  '장승배기',
  '신대방삼거리',
  '보라매',
  '신풍',
  '대림',
  '남구로',
  '가산디지털단지',
  '철산',
  '광명사거리',
  '천왕',
  '온수',
  '암사역사공원',
  '암사',
  '천호',
  '강동구청',
  '몽촌토성',
  '잠실',
  '석촌',
  '송파',
  '가락시장',
  '문정',
  '장지',
  '복정',
  '산성',
  '남한산성입구',
  '단대오거리',
  '신흥',
  '수진',
  '모란',
  '남위례',
]);

/** 역명이 혼잡도 API 지원 대상인지 (O(1)) */
export function isCongestionSupported(stationName: string): boolean {
  return CONGESTION_SUPPORTED_NAMES.has(stationName.trim());
}
